export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const AUTH_ROUTE = '/auth-myAccaunt'
export const ADMIN_ROUTE = '/admin'
export const ADD_ROUTE = '/addItems-onlyForAdminNot-only'
export const UNDEFINED = '/undefinedPage'
export const BASKET_PAGE = '/basketPageSeeAndOrder'
export const EXPLORE_ROUTE = '/exploreItem'
export const SHOW_ROUTE = '/showAlltypeOfitems'
export const ALLITEMS_ROUTE = '/allitemsShow'
export const FEED_ROUTE = '/feedbackPage'
export const ADDADRESS_ROUTE = '/addAnewAdress'
export const PERSONAL_ROUTE = '/personalInformation'

export const MESSAGE_ROUTE = '/messagePageOnlyforAdmin'